In [1]:
#!pip install splinter

In [2]:
# Dependencies
from bs4 import BeautifulSoup
import requests
import pymongo
import pandas as pd
from splinter import Browser
from webdriver_manager.chrome import ChromeDriverManager
import numpy as np
import matplotlib.pyplot as plt

In [3]:
freeThrowPct = "https://www.teamrankings.com/ncaa-basketball/stat/free-throw-pct"
astTo = "https://www.teamrankings.com/ncaa-basketball/stat/assist--per--turnover-ratio"
eFG = "https://www.teamrankings.com/ncaa-basketball/stat/effective-field-goal-pct"
defReb = "https://www.teamrankings.com/ncaa-basketball/stat/defensive-rebounding-pct"
offReb = "https://www.teamrankings.com/ncaa-basketball/stat/offensive-rebounding-pct"
oppEFG = "https://www.teamrankings.com/ncaa-basketball/stat/opponent-effective-field-goal-pct"
defEff = "https://www.teamrankings.com/ncaa-basketball/stat/defensive-efficiency"
teams = "https://www.teamrankings.com/ncaa-basketball/ranking/predictive-by-other"

In [4]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280

[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_mac64.zip
[WDM] - Driver has been saved in cache [/Users/jerkardash/.wdm/drivers/chromedriver/mac64/87.0.4280.88]

In [5]:
# browser.visit(teams)
# html = browser.html
# soup = BeautifulSoup(html, 'html.parser')
# table = soup.find_all('table')
# df_teams = pd.read_html(str(table))[0]

In [6]:
# df_teams["Team"] = df_teams["Team"].str.rsplit(" ", n=1, expand=True)
# df_teams = df_teams.head(100)

In [7]:
browser.visit(freeThrowPct)

In [8]:
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [9]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_ft = df.rename(columns={
    "2020": "Free Throw %"
})
#df_ft

In [10]:
browser.visit(astTo)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [11]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_ast = df.rename(columns={
    "2020": "AST/TO"
})
#df_ast

In [12]:
merged = df_ft.merge(df_ast, on="Team")
merged

             Team Free Throw % AST/TO
0        Colorado        83.4%  1.218
1    Oral Roberts        81.4%  0.970
2        Virginia        80.4%  1.474
3       Lafayette        80.4%  1.468
4         Detroit        80.4%  1.245
..            ...          ...    ...
352        U Penn           --     --
353      Columbia           --     --
354     Dartmouth           --     --
355       Harvard           --     --
356     Princeton           --     --

[357 rows x 3 columns]

In [13]:
browser.visit(eFG)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [14]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_eFG = df.rename(columns={
    "2020": "EFG %"
})
#df_eFG

In [15]:
merged = merged.merge(df_eFG, on="Team")
#merged

In [16]:
browser.visit(defReb)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [17]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_defReb = df.rename(columns={
    "2020": "Def Reb %"
})
#df_defReb

In [18]:
merged = merged.merge(df_defReb, on="Team")
#merged

In [19]:
browser.visit(offReb)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [20]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_offReb = df.rename(columns={
    "2020": "Off Reb %"
})
#df_offReb

In [21]:
merged = merged.merge(df_offReb, on="Team")
#merged

In [22]:
browser.visit(oppEFG)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [23]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_oppEFG = df.rename(columns={
    "2020": "Opp EFG %"
})
#df_oppEFG

In [24]:
merged = merged.merge(df_oppEFG, on="Team")
#merged

In [25]:
browser.visit(defEff)
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [26]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
df = df[["Team", "2020"]]
df_defEff = df.rename(columns={
    "2020": "Def Eff"
})
#df_defEff

In [27]:
fatdood_data = merged.merge(df_defEff, on="Team")
#fatdood_data

In [28]:
browser.quit()

In [29]:
df = fatdood_data

In [30]:
df.dtypes

Team            object
Free Throw %    object
AST/TO          object
EFG %           object
Def Reb %       object
Off Reb %       object
Opp EFG %       object
Def Eff         object
dtype: object

In [31]:
df.loc[df["Free Throw %"] == "--", 'Free Throw %'] = np.nan
df = df.dropna()

In [32]:
df["Free Throw %"] = df["Free Throw %"].str[:-1]
df["Free Throw %"] = df["Free Throw %"].astype(float)

df["AST/TO"] = df["AST/TO"].astype(float)

df["EFG %"] = df["EFG %"].str[:-1]
df["EFG %"] = df["EFG %"].astype(float)

df["Def Reb %"] = df["Def Reb %"].str[:-1]
df["Def Reb %"] = df["Def Reb %"].astype(float)

df["Off Reb %"] = df["Off Reb %"].str[:-1]
df["Off Reb %"] = df["Off Reb %"].astype(float)

df["Opp EFG %"] = df["Opp EFG %"].str[:-1]
df["Opp EFG %"] = df["Opp EFG %"].astype(float)

df["Def Eff"] = df["Def Eff"].astype(float)

<ipython-input-32-85033e6397f4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Free Throw %"] = df["Free Throw %"].str[:-1]
<ipython-input-32-85033e6397f4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Free Throw %"] = df["Free Throw %"].astype(float)
<ipython-input-32-85033e6397f4>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["AST/TO"] = df["AST/TO"].astype(float)
<ipython-input-32-85033e6397f4>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["EFG %"] = df["EFG %"].str[:-1]
<ipython-input-32-85033e6397f4>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["EFG %"] = df["EFG %"].astype(float)
<ipython-input-32-85033e6397f4>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Def Reb %"] = df["Def Reb %"].str[:-1]
<ipython-input-32-85033e6397f4>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Def Reb %"] = df["Def Reb %"].astype(float)
<ipython-input-32-85033e6397f4>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Off Reb %"] = df["Off Reb %"].str[:-1]
<ipython-input-32-85033e6397f4>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Off Reb %"] = df["Off Reb %"].astype(float)
<ipython-input-32-85033e6397f4>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Opp EFG %"] = df["Opp EFG %"].str[:-1]
<ipython-input-32-85033e6397f4>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Opp EFG %"] = df["Opp EFG %"].astype(float)
<ipython-input-32-85033e6397f4>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Def Eff"] = df["Def Eff"].astype(float)

In [33]:
ft_mean = df["Free Throw %"].mean()
ast_mean = df["AST/TO"].mean()
efg_mean = df["EFG %"].mean()
defReb_mean = df["Def Reb %"].mean()
offReb_mean = df["Off Reb %"].mean()
oefg_mean = df["Opp EFG %"].mean()
defEff_mean = df["Def Eff"].mean()

In [34]:
ft_sd = df["Free Throw %"].std()
ast_sd = df["AST/TO"].std()
efg_sd = df["EFG %"].std()
defReb_sd = df["Def Reb %"].std()
offReb_sd = df["Off Reb %"].std()
oefg_sd = df["Opp EFG %"].std()
defEff_sd = df["Def Eff"].std()

In [35]:
df["FT Score"] = (df["Free Throw %"] - ft_mean)/ft_sd
df["AST Score"] = (df["AST/TO"] - ast_mean)/ast_sd
df["EFG Score"] = (df["EFG %"] - efg_mean)/efg_sd
df["Def Reb Score"] = (df["Def Reb %"] - defReb_mean)/defReb_sd
df["Off Reb Score"] = (df["Off Reb %"] - offReb_mean)/offReb_sd
df["Opp EFG Score"] = (df["Opp EFG %"] - oefg_mean)/oefg_sd
df["Def Eff Score"] = (df["Def Eff"] - defEff_mean)/defEff_sd

<ipython-input-35-269cc6e63eef>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["FT Score"] = (df["Free Throw %"] - ft_mean)/ft_sd
<ipython-input-35-269cc6e63eef>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["AST Score"] = (df["AST/TO"] - ast_mean)/ast_sd
<ipython-input-35-269cc6e63eef>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["EFG Score"] = (df["EFG %"] - efg_mean)/efg_sd
<ipython-input-35-269cc6e63eef>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Def Reb Score"] = (df["Def Reb %"] - defReb_mean)/defReb_sd
<ipython-input-35-269cc6e63eef>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Off Reb Score"] = (df["Off Reb %"] - offReb_mean)/offReb_sd
<ipython-input-35-269cc6e63eef>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Opp EFG Score"] = (df["Opp EFG %"] - oefg_mean)/oefg_sd
<ipython-input-35-269cc6e63eef>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Def Eff Score"] = (df["Def Eff"] - defEff_mean)/defEff_sd

In [36]:
#df.to_excel("fatdood.xlsx", sheet_name='Sheet_name_1')

In [58]:
df

,Team,Free Throw %,AST/TO,EFG %,Def Reb %,Off Reb %,Opp EFG %,Def Eff,FT Score,AST Score,EFG Score,Def Reb Score,Off Reb Score,Opp EFG Score,Def Eff Score,Score
97,Gonzaga,73.2,1.522,61.1,78.9,29.0,47.5,0.900,0.553016,2.430703,3.464495,1.423889,0.684347,-0.910058,-1.624553,1.584437
82,Houston,73.6,1.207,50.8,76.5,39.8,42.4,0.847,0.647535,0.962765,0.239058,0.736779,3.020952,-2.639393,-2.544303,1.541541
49,Colgate,75.2,1.667,56.8,76.4,25.8,45.0,0.910,1.025610,3.106421,2.117953,0.708149,-0.007981,-1.757771,-1.451015,1.451277
28,Michigan,76.9,1.286,55.7,78.6,28.0,44.0,0.926,1.427315,1.330915,1.773489,1.338000,0.467994,-2.096856,-1.173355,1.372561
223,Saint Louis,69.3,1.498,52.3,80.6,34.4,47.7,0.917,-0.368541,2.318860,0.708782,1.910592,1.852649,-0.842241,-1.329539,1.227732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,Air Force,69.5,0.845,52.4,65.7,14.0,57.0,1.104,-0.321282,-0.724199,0.740097,-2.355217,-2.560938,2.311252,1.915616,-1.349773
325,San Jose St,64.6,0.723,44.4,65.6,18.3,51.7,1.109,-1.479137,-1.292734,-1.765097,-2.383847,-1.630623,0.514100,2.002385,-1.581132
339,S Car State,62.1,0.571,44.8,66.8,24.1,55.4,1.065,-2.069879,-2.001072,-1.639837,-2.040292,-0.375780,1.768716,1.238819,-1.590628
345,Miss Val St,58.1,0.594,43.5,65.0,15.8,54.6,1.159,-3.015066,-1.893890,-2.046931,-2.555624,-2.171504,1.497448,2.870074,-2.292934
209,Chicago St,69.8,0.636,41.3,63.7,13.7,60.1,1.221,-0.250393,-1.698164,-2.735859,-2.927809,-2.625844,3.362417,3.946007,-2.506642

In [67]:
df["Score"] = (df["FT Score"] + df["AST Score"] + df["EFG Score"] + df["Def Reb Score"] + df["Off Reb Score"] - df["Opp EFG Score"] - df["Def Eff Score"])/7

In [68]:
df = df.sort_values(by="Score", ascending=False)
df

,Team,Free Throw %,AST/TO,EFG %,Def Reb %,Off Reb %,Opp EFG %,Def Eff,FT Score,AST Score,EFG Score,Def Reb Score,Off Reb Score,Opp EFG Score,Def Eff Score,Score
97,Gonzaga,73.2,1.522,61.1,78.9,29.0,47.5,0.900,0.553016,2.430703,3.464495,1.423889,0.684347,-0.910058,-1.624553,1.584437
82,Houston,73.6,1.207,50.8,76.5,39.8,42.4,0.847,0.647535,0.962765,0.239058,0.736779,3.020952,-2.639393,-2.544303,1.541541
28,Michigan,76.9,1.286,55.7,78.6,28.0,44.0,0.926,1.427315,1.330915,1.773489,1.338000,0.467994,-2.096856,-1.173355,1.372561
49,Colgate,75.2,1.667,56.8,76.4,25.8,45.0,0.910,1.025610,2.500000,2.117953,0.708149,-0.007981,-1.757771,-1.451015,1.364646
223,Saint Louis,69.3,1.498,52.3,80.6,34.4,47.7,0.917,-0.368541,2.318860,0.708782,1.910592,1.852649,-0.842241,-1.329539,1.227732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,Air Force,69.5,0.845,52.4,65.7,14.0,57.0,1.104,-0.321282,-0.724199,0.740097,-2.355217,-2.560938,2.311252,1.915616,-1.349773
325,San Jose St,64.6,0.723,44.4,65.6,18.3,51.7,1.109,-1.479137,-1.292734,-1.765097,-2.383847,-1.630623,0.514100,2.002385,-1.581132
339,S Car State,62.1,0.571,44.8,66.8,24.1,55.4,1.065,-2.069879,-2.001072,-1.639837,-2.040292,-0.375780,1.768716,1.238819,-1.590628
345,Miss Val St,58.1,0.594,43.5,65.0,15.8,54.6,1.159,-3.015066,-1.893890,-2.046931,-2.555624,-2.171504,1.497448,2.870074,-2.292934
209,Chicago St,69.8,0.636,41.3,63.7,13.7,60.1,1.221,-0.250393,-1.698164,-2.735859,-2.927809,-2.625844,3.362417,3.946007,-2.506642

In [69]:
df.to_excel("fatdood.xlsx", sheet_name='Sheet_name_1')